name: Generate Futuristic Pixel Snake

on:
  schedule:
    - cron: "0 0 * * *"   # se ejecuta todos los días
  workflow_dispatch:      # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Futuristic Snake
        uses: Platane/snk@v3
        with:
          github_user_name: eduardopertuz1712
          outputs: |
            dist/github-contribution-grid-snake.svg
          colors: "#0ff,#ff00ff,#00ff9f"  # colores neon: cyan, magenta, verde neón
          background: "#0a0a0a"            # fondo oscuro cyber

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
